### ISSUE TITLE
Optimizing with plugin fails due to asynchronous load

### ISSUE THREAD

**Issue by purge** [ractivejs/rv#4]
See 'build considerations' in http://requirejs.org/docs/plugins.html. text.get is asynchronous.

**Comment by purge** [comment]
This appears to have only properly broken in 2.1.9.

**Comment by Rich-Harris** [comment]
I'm not totally sure I follow - it works for me with 2.1.9, at what stage are you getting the error and what does it say?

**Comment by Rich-Harris** [comment]
Closing - this was fixed some time ago AFAICT
