### ISSUE TITLE
There is a simple complete sample?

### ISSUE THREAD

**Issue by lguzzon** [ractivejs/rv#5]

**Comment by akralj** [comment]
+1. I tried to use ractive.js with require.js as well, but failed, because I do not know require.js at all. Could anyone be so kind to just upload a minimal example, which can be just used with require.js.  Thanks a lot. 
andrej

**Comment by Rich-Harris** [comment]
I've just created a sample app here:

https://github.com/Rich-Harris/require-ractive-plugin/tree/master/sample

RequireJS is tricky to get the hang of but worth it! Good luck

**Comment by akralj** [comment]
That was quick. Thank you so much Rich for this sample and this beautiful library. I'm getting into it now. 
Cheers andrej

**Comment by Rich-Harris** [comment]
My pleasure! Will close this issue

**Comment by lguzzon** [comment]
Thanks
